# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/collections

SRC=  flags.ml globals.ml \
  ast.ml meta_ast.ml \
  opcode.ml meta_opcode.ml \
  dumper.ml \
  compile.ml \
  runtime.ml \
  pattern.ml \
  fn.ml var.ml prompt.ml status.ml path.ml process.ml error.ml \
  parser.ml lexer.ml parse.ml \
  builtin.ml \
  op_repl.ml op_process.ml \
  interpreter.ml main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/collections/lib.cma $TOP/lib_core/commons/lib.cma

PROG=rc

<$TOP/mkconfig
<$TOP/mkprog

beforedepend:V: lexer.ml parser.ml parser.mli


depend:V: beforedepend

distclean:V: clean
	rm -f lexer.ml
	rm -f parser.ml parser.mli parser.output

lexer.ml:D: lexer.mll
	$OCAMLLEX $prereq

parser.ml parser.mli: parser.mly
	$OCAMLYACC $prereq


loc:V:
	mk distclean
	wc -l *.ml*
