TOP=..

INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/collections

SRC=  flags.ml globals.ml \
  ast.ml meta_ast.ml \
  opcode.ml meta_opcode.ml \
  dumper.ml \
  compile.ml \
  runtime.ml \
  pattern.ml \
  fn.ml var.ml prompt.ml status.ml path.ml process.ml error.ml \
  Parser.ml Lexer.ml parse.ml \
  builtin.ml \
  op_repl.ml op_process.ml \
  interpreter.ml main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/collections/lib.cma $TOP/lib_core/commons/lib.cma

PROG=rc

<$TOP/mkconfig
<$TOP/mkprog
<$TOP/mkparser
