TOP=..

INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/collections

#coupling: library stanza in dune file
SRC=  Flags.ml Globals.ml \
  Ast.ml Meta_ast.ml \
  Opcode.ml Meta_opcode.ml \
  Dumper_.ml \
  Compile.ml \
  Runtime.ml \
  Pattern.ml \
  Fn.ml Var.ml Prompt.ml Status.ml Path.ml Process.ml Error.ml \
  Parser.ml Lexer.ml Parse.ml \
  Builtin.ml \
  Op_repl.ml Op_process.ml \
  Interpreter.ml Main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/collections/lib.cma $TOP/lib_core/commons/lib.cma

PROG=rc

<$TOP/mkconfig
<$TOP/mkprog
<$TOP/mkparser
