(*s: Opcode.ml *)
(* Copyright 2016, 2025 Yoann Padioleau, see copyright.txt *)

(*s: type [[Opcode.operation]] *)
(* Operations generated by the compiler. 
 * 
 * Semantic of comments below:
 *  - Arguments on stack (...)
 *  - Arguments in line [...]
 *  - Code in line with jump around {...}
 * 
 * alt: type operation = ((unit -> unit) * string)
 *)
type operation =

  (* Stack (argv) *)
  | Mark
  | Word (* [string] *)
  | Popm (* (value) *)
  (*s: [[Opcode.operation]] other stack cases *)
  | Count (* (name) *)
  | Concatenate (* (left)(right) *)
  | Stringify (* (name) *)
  (*e: [[Opcode.operation]] other stack cases *)

  (* Variable *)
  | Assign (* (name)(val) *)
  | Dollar (* (name) *)
  (*s: [[Opcode.operation]] other variable cases *)
  | Index  (* ??? *)
  | Local (* (name)(val) *)
  | Unlocal (* *)
  (*e: [[Opcode.operation]] other variable cases *)

  (* Process! *)
  | Simple (* (args) *)
  | Async  (* {... Xreturn} *)

  (* Control flow *)
  | If 
  | IfNot
  (* While are compiled in jumps *)
  | Jump  (* [addr] *)
  | Exit 
  (*s: [[Opcode.operation]] other control cases *)
  | Return
  (*x: [[Opcode.operation]] other control cases *)
  | For   (* (var, list){... Xreturn} *)
  (*x: [[Opcode.operation]] other control cases *)
  | Case  (* (pat, value){...} *)
  (*e: [[Opcode.operation]] other control cases *)

  (* Boolean return status  *)
  | Wastrue
  | Not
  | False (* {...} *)
  | True  (* {...} *)
  | Match (* (pat, str) *)

  (* Redirections *)
  | Read (* (file)[fd] *)
  | Write (* (file)[fd] *)
  | Append (* (file)[fd] *)
  (*s: [[Opcode.operation]] other redirection cases *)
  | ReadWrite (* (file)[fd] *)
  | Close  (* [fd] *)
  | Dup    (* [fd0 fd1] *)
  | Popredir (* *)
  (*e: [[Opcode.operation]] other redirection cases *)

  (* Pipes *)
  | Pipe (* [i j]{... Xreturn}{... Xreturn} *)
  (*s: [[Opcode.operation]] other pipe cases *)
  | PipeWait (* argument passed through Thread.pid *)
  | PipeFd (* [type]{... Xreturn} *)
  (*e: [[Opcode.operation]] other pipe cases *)

  (* Functions *)
  | Fn (* (name){... Xreturn } *)

  (*s: [[Opcode.operation]] other cases *)
  (* Globbing *)
  | Glob (* (value?) *)
  (*x: [[Opcode.operation]] other cases *)
  (* Error management *)
  | Eflag
  (*x: [[Opcode.operation]] other cases *)
  | DelFn (* (name) *)
  (* less: RdFn *)
  (*x: [[Opcode.operation]] other cases *)
  (* ?? *)
  | Subshell (* {... Xexit} *)
  (*x: [[Opcode.operation]] other cases *)
  | Backquote (* {... Xreturn} *)
  (*e: [[Opcode.operation]] other cases *)

  | REPL (* *)
(*e: type [[Opcode.operation]] *)
(*s: type [[Opcode.opcode]] *)
type opcode =
  | F of operation
  | I of int
  | S of string
(*e: type [[Opcode.opcode]] *)
(*s: type [[Opcode.codevec]] *)
type codevec = opcode array
(*e: type [[Opcode.codevec]] *)
(*e: Opcode.ml *)
