# -*- sh -*-
TOP=../..

SRC=

INCLUDES=-I $TOP/commons2 \
  -I $TOP/lib_graphics/geometry -I $TOP/lib_graphics/draw

LIBS=$TOP/commons2/lib.cma $TOP/lib_graphics/geometry/lib.cma \
 $TOP/lib_graphics/draw/lib.cma

SYSLIBS=unix.cma threads.cma str.cma
CCLIBS= -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libunix.a\
        -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libstr.a\
        -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libthreads.a\
        -cclib /home/pad/github/fork-ocaml/byterun/main.8

PROG=test_rio_graph_app1

<$TOP/mkconfig2
<$TOP/mkprog
