# -*- sh -*-
TOP=../..

INCLUDES=-I $TOP/lib_core/commons \
  -I $TOP/lib_graphics/geometry -I $TOP/lib_graphics/draw \
  -I $TOP/lib_graphics/input
LIBS=$TOP/lib_core/commons/lib.cma $TOP/lib_core/regexps/lib.cma \
 $TOP/lib_graphics/geometry/lib.cma $TOP/lib_graphics/draw/lib.cma \
  $TOP/lib_graphics/input/lib.cma
SYSLIBS=unix.cma threads.cma

PTOP=$TOP/principia
objtype=386
#alt:</$TOP/mkconfig
CAMLLIB=$PTOP/ROOT/$objtype/lib/ocaml
OCAMLC=/usr/local/bin/ocamlrun /usr/local/bin/ocamlc $INCLUDES
CCLIBS= -cclib $CAMLLIB/libunix.a -cclib $CAMLLIB/libthreads.a -cclib $CAMLLIB/main.8


PROGS=hellorio
#test_rio_graph_app1  test_rio_console_app1

all:V: $PROGS

hellorio: $LIBS hellorio.ml
        $OCAMLC -thread  -verbose $SYSLIBS -custom $prereq -o $target $CCLIBS

test_rio_graph_app1: test_rio_graph_app1.cmo
	$OCAMLC $LINKFLAGS $EXTRALINKFLAGS $INCLUDES $SYSLIBS $LIBS $prereq $CCLIBS -o $target

test_rio_console_app1: test_rio_console_app1.cmo
	$OCAMLC $LINKFLAGS $EXTRALINKFLAGS $INCLUDES $SYSLIBS $LIBS $prereq $CCLIBS -o $target


clean nuke:V:
	rm -f $PROGS *.cm[ioxa] *.cmxa  *.o *.a  *.annot *.cmt*
	rm -f *~ .*~ *.exe gmon.out *.output

ROOT=/home/pad/plan9/ROOT/
test:V:
	cp $PROGS $ROOT/tests/xxx/
    cd /home/pad/plan9; make disk; make run


<$TOP/mkfiles/mkcommon
<.depend
