TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml 
#SYNCWEBFLAGS=-debug

DOC=omk
DOC_EXTRA=control_flow.tex
VERSION=1
D=..
SRC_ML=\
  $D/Parse.ml \
  $D/Shellenv.ml $D/Shell.ml \
  $D/Percent.ml $D/Env.ml  $D/Eval.ml \
  $D/File.ml $D/Graph.ml \
  $D/Scheduler.ml $D/Outofdate.ml \
  $D/CLI.ml
SRC_ML_NO_MLI=$D/Ast.ml $D/Globals.ml $D/Flags.ml $D/Main.ml $D/Rules.ml $D/Job.ml

# also $D/Parser.mly but use different -lang
SRC_VIEWS= $SRC_ML ${SRC_ML:%.ml=%.mli} $SRC_ML_NO_MLI $D/Lexer.mll $D/Lexer.mli

SRC_ORIG=omk.nw Intro.nw omk_extra.nw


<$TOP/docs/latex/mkcommon

sync_yacc:VI:
        $SYNCWEB -md5sum_in_auxfile -less_marks -lang ocamlyacc  $SRC_ORIG \
            $D/Parser.mly

control_flow.tex: control_flow.dot
   dot2tex $prereq --figonly > $target


# steps to build index:
# - switch to dune 2.7 in xix/dune-project if needed
# - remove wrapped true in xix/mk/dune file
# - comment open Xix_mk in xix/mk/Main.ml
# - cd ~/xix; mk nuke; make clean
# # produce .cmt for all of xix (dune build _build/.../mk is not enough)
# - make build-dune
# - rm -rf _build/.../mk/tests
# - codegraph_build -lang cmt .
# # look if codegraph looks ok with:
# - cg .
# - cd mk/docs
# - mk index
# - mk pdf
# => DONE! Mk.pdf should now have indexes!
index:V:
    $INDEXER -lang cmt $TOP \
    | grep -v 'TODO_NO_SOURCE_FOUND' \
    | grep  'mk/' \
    > defs_and_uses.list.new
    mv defs_and_uses.list.new defs_and_uses.list
