TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml 
#SYNCWEBFLAGS=-debug

DOC=occ
#DOC_EXTRA=control_flow.tex
VERSION=1
D=..
D2=$TOP/macroprocessor
SRC_ML=\
  $D/Arch5.ml $D/Dumper_.ml $D/Error.ml \
  $D/Parse.ml $D/Check.ml $D/Typecheck.ml \
  $D/Eval_const.ml $D/Rewrite.ml $D/Codegen5.ml \
  $D/CLI.ml \
  $D2/Location_cpp.ml $D2/Parse_cpp.ml

SRC_ML_NO_MLI=\
  $D/Arch_compiler.ml \
  $D/Flags.ml $D/Globals.ml \
  $D/Ast.ml $D/Type.ml $D/Storage.ml \
  $D/Main.ml \
  $D2/Flags_cpp.ml $D2/Ast_cpp.ml $D2/Preprocessor.ml

# also $D/Parser.mly but use different -lang
SRC_VIEWS= $SRC_ML ${SRC_ML:%.ml=%.mli} $SRC_ML_NO_MLI \
 $D/Lexer.mll $D2/Lexer_cpp.mll

SRC_ORIG=occ.nw Intro.nw occ_extra.nw


<$TOP/docs/latex/mkcommon

sync_yacc:VI:
        $SYNCWEB -md5sum_in_auxfile -less_marks -lang ocamlyacc  $SRC_ORIG \
            $D/Parser.mly

control_flow.tex: control_flow.dot
   dot2tex $prereq --figonly > $target


# steps to build index: see builder/docs/mkfile
index:V:
#    $INDEXER -lang cmt $TOP \
#    | grep -v 'TODO_NO_SOURCE_FOUND' \
#    | grep  'mk/' \
#    > defs_and_uses.list.new
#    mv defs_and_uses.list.new defs_and_uses.list
