# Build and test XiX with ocaml-light on Ubuntu Linux.

# see https://github.com/aryx/ocaml-light/blob/main/Dockerfile
FROM padator/ocaml-light

WORKDIR /xix

# Now let's build from source
COPY . .

# Bootstrap
ENV use_ocaml_light="yes"
RUN ./bootstrap-mk.sh

# Full build
# TODO
