# -*- sh -*-
# The parser generator

TOP=..
INCLUDES=-I $TOP/lib_core/collections -I $TOP/lib_parsing

SRC= ast.ml\
 parser.ml lexer.ml\
 check.ml\
 lr0.ml first_follow.ml lrtables.ml slr.ml lalr.ml \
 output.ml dump.ml \
 tests.ml main.ml

# need str.cma and commons/lib.cma because of Common.Stack_.nth
# but we could inline this function in parsing_.ml to avoid those deps.
SYSLIBS=str.cma
LIBS=$TOP/lib_core/collections/lib.cma $TOP/lib_core/commons/lib.cma \
  $TOP/lib_parsing/lib.cma

PROG=ocamlyacc

<$TOP/mkconfig
<$TOP/mkprog

#<$TOP/mkparser

AUTOGEN=lexer.ml parser.ml parser.mli
NUKEFILES=$AUTOGEN

beforedepend:V: $AUTOGEN
depend:V: beforedepend

lexer.ml:D: lexer.mll
	$OCAMLLEX $prereq
parser.ml parser.mli: parser.mly
	$OCAMLYACC $prereq
	perl -p -i -e 's#/\*\(\*[sex]: .* \*\)\*/##' parser.ml
#pad: this  perl thing is just because ocamlyacc does not handle well
# syncweb special comment at the very end


loc:V:
   wc -l globals.ml lexer_asm5.mll parser_asm5.mly parse_asm5.ml* main.ml $TOP/formats/objects/ast_asm5.ml $TOP/formats/objects/object_code5.ml*
