# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/commons

SRC= globals.ml flags.ml \
  ast.ml \
  parser.ml lexer.ml parse.ml \
  percent.ml  shellenv.ml env.ml  rules.ml \
  eval.ml \
  graph.ml \
  job.ml \
  scheduler.ml shell.ml \
  main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/commons/lib.cma

PROG=mk

<$TOP/mkone

beforedepend:V: lexer.ml parser.ml parser.mli


depend:V: beforedepend

distclean:V: clean
	rm -f lexer.ml
	rm -f parser.ml parser.mli parser.output

lexer.ml: lexer.mll
	$OCAMLLEX $prereq

parser.ml parser.mli: parser.mly
	$OCAMLYACC $prereq


loc:V:
	mk distclean
	wc -l *.ml*
