# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/collections

SRC= globals.ml flags.ml \
  ast.ml   parser.ml lexer.ml parse.ml \
  shellenv.ml shell.ml \
  percent.ml env.ml rules.ml   eval.ml \
  file.ml graph.ml \
  job.ml   scheduler.ml outofdate.ml \
  main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/collections/lib.cma $TOP/lib_core/commons/lib.cma

PROG=mk

<$TOP/mkconfig
<$TOP/mkprog

beforedepend:V: lexer.ml parser.ml parser.mli


depend:V: beforedepend

distclean:V: clean
	rm -f lexer.ml
	rm -f parser.ml parser.mli parser.output

lexer.ml:D: lexer.mll
	$OCAMLLEX $prereq

parser.ml parser.mli: parser.mly
	$OCAMLYACC $prereq


loc:V:
	mk distclean
	wc -l *.ml*
