TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=5a_
LDLIBS=-lbio -l9 -lm
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../5l_/5.out.h\
	y.tab.h\
	a.h\

YFILES=a.y

YFLAGS=-D1 -d

<$TOP/mkfiles/mkone

lex.$O:	../cc/macbody ../cc/lexbody
