# -*- sh -*-
TOP=../../..

INCLUDES=-I $TOP/commons2 \
  -I $TOP/lib_graphics/geometry -I $TOP/lib_graphics/draw

LIBS=$TOP/commons2/lib.cma $TOP/lib_graphics/geometry/lib.cma \
 $TOP/lib_graphics/draw/lib.cma

SYSLIBS=unix.cma threads.cma str.cma
CCLIBS= -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libunix.a\
        -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libstr.a\
        -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libthreads.a\
        -cclib /home/pad/github/fork-ocaml/byterun/main.8

<$TOP/mkconfig2
</$objtype/mkfile

#############################################################################
# Toplevel targets
#############################################################################

PROGS=hellodraw test_font
#gen_font_default

all:V: $PROGS

hellodraw: $LIBS hellodraw.cmo
	$OCAMLC  -verbose $LINKFLAGS -o $target $SYSLIBS $prereq $CCLIBS

test_font: $LIBS test_font.cmo
	$OCAMLC  -verbose $LINKFLAGS -o $target $SYSLIBS $prereq $CCLIBS

# need to unset CAMLLIB above to be able to compile this program
gen_font_default: gen_font_default.ml ../font_default.ml
	ocamlc -g -I $TOP/commons -I ../ str.cma $TOP/commons/lib.cma ../font_default.ml gen_font_default.ml  -o testfont

clean:V:
	rm -f *.cma *.cmo *.cmi *.8 $PROGS

<$TOP/mkcommon
