# -*- sh -*-
TOP=../../..
#############################################################################
# Compilers
#############################################################################

OCAML=/home/pad/github/fork-ocaml
OCAMLC=$OCAML/byterun/ocamlrun $OCAML/ocamlc
OCAMLDEP=ocamldep

#############################################################################
# Config
#############################################################################

OCAMLINCLUDES=-I $TOP/commons2 -I $TOP/lib_system/plan9


OCAMLCFLAGS=$OCAMLINCLUDES -thread -g

OCAMLLDFLAGS=-thread -custom -g -I /home/pad/plan9/ROOT/$objtype/lib/ocaml

# for the linker
#CAMLLIB=/usr/local/lib/ocaml
CAMLLIB=/home/pad/plan9/ROOT/usr/local/lib/ocaml

LIBS=$TOP/commons2/commons.cma $TOP/lib_system/plan9/plan9.cma

SYSLIBS=unix.cma threads.cma str.cma
CCLIBS= \
        -cclib $TOP/lib_system/plan9/libplan9.a\
        -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libunix.a\
        -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libstr.a\
        -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libthreads.a\
        -cclib /home/pad/github/fork-ocaml/byterun/main.8

#############################################################################
# Toplevel targets
#############################################################################

PROGS=test_bind test_mount

all:V: $PROGS

test_bind: test_bind.cmo
	$OCAMLC  -verbose $OCAMLLDFLAGS -o $target $SYSLIBS $LIBS $prereq $CCLIBS

test_mount: test_mount.cmo
	$OCAMLC  -verbose $OCAMLLDFLAGS -o $target $SYSLIBS $LIBS $prereq $CCLIBS

clean:V:
	rm -f *.cma *.cmo *.cmi *.8 $PROGS

depend:V:
	$OCAMLDEP $OCAMLINCLUDES *.ml* */*.ml* | grep -v -e '.* :$' > .depend

ROOT=/home/pad/plan9/ROOT/
test:V:
	cp $PROGS $ROOT/tests/xxx/
    cd /home/pad/plan9; make disk; make run

#############################################################################
# Meta rules
#############################################################################

%.cmo: %.ml
	$OCAMLC $OCAMLCFLAGS -c $stem.ml

%.cmi: %.mli
	$OCAMLC $OCAMLCFLAGS -c $stem.mli


#############################################################################
<.depend
