# -*- sh -*-
TOP=../..

INCLUDES=-I $TOP/lib_core/commons2 -I ../geometry

SRC= Channel.ml Color.ml \
     Draw_marshal.ml Display.ml Image.ml \
     Draw_ipc.ml \
     Draw.ml \
     Line.ml Polygon.ml Ellipse.ml Arc.ml \
     Fontchar.ml Subfont.ml Font.ml Font_default.ml Text.ml \
     Baselayer.ml Layer.ml \
     Draw_rio.ml

<$TOP/mkconfig2
<$TOP/mklib

