# -*- sh -*-
TOP=../..

INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/regexps \
  -I $TOP/lib_graphics/draw -I $TOP/lib_graphics/geometry \

SRC= Cursor.ml Mouse.ml Keyboard.ml

EXTRA_FLAGS=-thread

<$TOP/mkconfig
<$TOP/mkfiles/mklib
