# -*- sh -*-
TOP=../..

#TODO: should use -I +threads instead of full path below
INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/regexps \
  -I $TOP/lib_graphics/draw -I $TOP/lib_graphics/geometry \
  -I +threads -I /usr/local/lib/ocaml/
SRC= Cursor.ml Mouse.ml Keyboard.ml

<$TOP/mkconfig
<$TOP/mkfiles/mklib
