TOP=../../../..

<$TOP/mkconfig

INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/system/plan9
LIBS=$TOP/lib_core/commons/lib.cma $TOP/lib_core/system/plan9/lib.cma
SYSLIBS=unix.cma threads.cma

CCLIBS_EXTRA=-cclib $TOP/lib_core/system/plan9/libplan9.a

#############################################################################
# Toplevel targets
#############################################################################

PROGS=test_bind test_mount test_bind_c test_bind_ape

all:V: $PROGS

test_bind: $LIBS test_bind.ml
	$OCAMLC $INCLUDES -thread -custom -verbose $OCAMLLDFLAGS -o $target $SYSLIBS $prereq $CCLIBS $CCLIBS_EXTRA

test_mount: $LIBS test_mount.ml
	$OCAMLC $INCLUDES -thread -custom -verbose $OCAMLLDFLAGS -o $target $SYSLIBS $prereq $CCLIBS $CCLIBS_EXTRA

clean nuke:V:
	rm -f *.cma *.cmo *.cmi *.8 $PROGS

depend:V:
	$OCAMLDEP $OCAMLINCLUDES *.ml* */*.ml* | grep -v -e '.* :$' > .depend

install:V:
	cp $PROGS $TOP/principia/ROOT/tests/bytecode/
	#cd /home/pad/principia; omk disk; omk run

test_bind_c: test_bind_c.c
	8c -I/home/pad/principia/include/ALL/ -I/home/pad/principia/include/arch/386/ test_bind_c.c
	8l -L/home/pad/principia/ROOT/386/lib/ -o test_bind_c test_bind_c.8 


CFLAGS=-FV -D_POSIX_SOURCE -D_PLAN9_SOURCE -DOS_PLAN9_APE -I$TOP/principia/APE/include -I$TOP/principia/APE/include/$objtype 

test_bind_ape: test_bind_ape.c
	pcc -v -o test_bind_ape $CFLAGS -L$TOP/principia/ROOT/386/lib/ape test_bind_ape.c 

#############################################################################
# Meta rules
#############################################################################

%.cmo: %.ml
	$OCAMLC $OCAMLCFLAGS -c $stem.ml

%.cmi: %.mli
	$OCAMLC $OCAMLCFLAGS -c $stem.mli


#############################################################################
<.depend
