TOP=../../../..

<$TOP/mkconfig

INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/system/plan9
LIBS=$TOP/lib_core/commons/lib.cma $TOP/lib_core/system/plan9/lib.cma
SYSLIBS=unix.cma threads.cma

CCLIBS_EXTRA=-cclib $TOP/lib_core/system/plan9/libplan9.a

#############################################################################
# Toplevel targets
#############################################################################

PROGS=test_bind test_mount

all:V: $PROGS

test_bind: $LIBS test_bind.ml
	$OCAMLC $INCLUDES -thread -custom -verbose $OCAMLLDFLAGS -o $target $SYSLIBS $prereq $CCLIBS $CCLIBS_EXTRA

test_mount: $LIBS test_mount.ml
	$OCAMLC $INCLUDES -thread -custom -verbose $OCAMLLDFLAGS -o $target $SYSLIBS $prereq $CCLIBS $CCLIBS_EXTRA

clean nuke:V:
	rm -f *.cma *.cmo *.cmi *.8 $PROGS

depend:V:
	$OCAMLDEP $OCAMLINCLUDES *.ml* */*.ml* | grep -v -e '.* :$' > .depend

test:V:
	cp $PROGS $TOP/principia/ROOT/tests/bytecode/
	cd /home/pad/principia; omk disk; omk run

#############################################################################
# Meta rules
#############################################################################

%.cmo: %.ml
	$OCAMLC $OCAMLCFLAGS -c $stem.ml

%.cmi: %.mli
	$OCAMLC $OCAMLCFLAGS -c $stem.mli


#############################################################################
<.depend
