  &&lbl_CONSTINT,
    &&lbl_CONST0, &&lbl_CONST1, &&lbl_CONST2, &&lbl_CONST3, 
    &&lbl_PUSHCONSTINT,
    &&lbl_PUSHCONST0, &&lbl_PUSHCONST1, &&lbl_PUSHCONST2, &&lbl_PUSHCONST3, 
  &&lbl_NEGINT, &&lbl_ADDINT, &&lbl_SUBINT, &&lbl_MULINT, &&lbl_DIVINT, &&lbl_MODINT,
  &&lbl_ANDINT, &&lbl_ORINT, &&lbl_XORINT, 
  &&lbl_LSLINT, &&lbl_LSRINT, &&lbl_ASRINT,
  &&lbl_EQ, &&lbl_NEQ, 
  &&lbl_LTINT, &&lbl_LEINT, &&lbl_GTINT, &&lbl_GEINT,
  &&lbl_OFFSETINT, &&lbl_OFFSETREF,
  &&lbl_ACC,
  &&lbl_PUSH,
  &&lbl_POP, 
  &&lbl_ASSIGN,
    &&lbl_ACC0, &&lbl_ACC1, &&lbl_ACC2, &&lbl_ACC3, &&lbl_ACC4, &&lbl_ACC5, &&lbl_ACC6, &&lbl_ACC7,
    &&lbl_PUSHACC0, &&lbl_PUSHACC1, &&lbl_PUSHACC2, &&lbl_PUSHACC3,
    &&lbl_PUSHACC4, &&lbl_PUSHACC5, &&lbl_PUSHACC6, &&lbl_PUSHACC7,
    &&lbl_PUSHACC, 
  &&lbl_ENVACC,
    &&lbl_ENVACC1, &&lbl_ENVACC2, &&lbl_ENVACC3, &&lbl_ENVACC4, 
    &&lbl_PUSHENVACC1, &&lbl_PUSHENVACC2, &&lbl_PUSHENVACC3, &&lbl_PUSHENVACC4, &&lbl_PUSHENVACC,
  &&lbl_ATOM,
  &&lbl_MAKEBLOCK,
    &&lbl_PUSHATOM,
    &&lbl_ATOM0, &&lbl_PUSHATOM0, 
    &&lbl_MAKEBLOCK1, &&lbl_MAKEBLOCK2, &&lbl_MAKEBLOCK3,
  &&lbl_GETFIELD,
  &&lbl_SETFIELD,
    &&lbl_GETFIELD0, &&lbl_GETFIELD1, &&lbl_GETFIELD2, &&lbl_GETFIELD3,
    &&lbl_SETFIELD0, &&lbl_SETFIELD1, &&lbl_SETFIELD2, &&lbl_SETFIELD3,
  &&lbl_GETGLOBAL, 
  &&lbl_SETGLOBAL, 
  &&lbl_GETGLOBALFIELD,
    &&lbl_PUSHGETGLOBAL, &&lbl_PUSHGETGLOBALFIELD, 
  &&lbl_BRANCH, 
  &&lbl_BRANCHIF, 
  &&lbl_BRANCHIFNOT, 
  &&lbl_SWITCH, 
  &&lbl_BOOLNOT,
  &&lbl_PUSH_RETADDR, 
  &&lbl_APPLY, 
  &&lbl_APPTERM, 
  &&lbl_RETURN, 
    &&lbl_APPLY1, &&lbl_APPLY2, &&lbl_APPLY3,
    &&lbl_APPTERM1, &&lbl_APPTERM2, &&lbl_APPTERM3, 
  &&lbl_DUMMY, 
  &&lbl_UPDATE,
  &&lbl_PUSHTRAP, 
  &&lbl_POPTRAP, 
  &&lbl_RAISE,
  &&lbl_CHECK_SIGNALS,
  &&lbl_C_CALLN,
    &&lbl_C_CALL1, &&lbl_C_CALL2, &&lbl_C_CALL3, &&lbl_C_CALL4, &&lbl_C_CALL5,
  &&lbl_GETSTRINGCHAR, &&lbl_SETSTRINGCHAR, 
  &&lbl_VECTLENGTH, &&lbl_GETVECTITEM, &&lbl_SETVECTITEM,
  &&lbl_RESTART, 
  &&lbl_GRAB,
  &&lbl_CLOSURE, 
  &&lbl_CLOSUREREC,
  &&lbl_STOP, &&lbl_EVENT, &&lbl_BREAK
