
hellodraw2: hellodraw2.cmo mkfile
	$OCAMLC -verbose $OCAMLLDFLAGS -thread -custom -o $target unix.cma threads.cma str.cma $LIBS hellorio.cmo -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libunix.a -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libstr.a -cclib /home/pad/plan9/ROOT/386/lib/ocaml/libthreads.a -cclib /home/pad/github/fork-ocaml/byterun/main.8
