TOP=../../..
<$TOP/mkconfig

INCLUDES=-I $TOP/lib_core/commons \
  -I $TOP/lib_graphics/geometry -I $TOP/lib_graphics/draw \
  -I $TOP/lib_graphics/input
LIBS=$TOP/lib_core/commons/lib.cma $TOP/lib_core/regexps/lib.cma \
 $TOP/lib_graphics/geometry/lib.cma $TOP/lib_graphics/draw/lib.cma \
 $TOP/lib_graphics/input/lib.cma
SYSLIBS=unix.cma threads.cma

PROGS=hellodraw2

all:V: $PROGS

hellodraw2: $LIBS hellodraw2.ml
	$OCAMLC $INCLUDES -thread -verbose $SYSLIBS -custom $prereq -o $target $CCLIBS

clean:V:
	rm -f *.cma *.cmo *.cmi *.8 $PROGS
