TOP=../..

DEPS=lib_core/commons \
 lib_gui/lib_graphics/geometry lib_gui/lib_graphics/input\
 lib_gui/lib_graphics/draw \
 lib_gui

SRC= hellogui.ml

PROG=hellogui
SYSLIBS=str.cma graphics.cma

INCLUDES=${DEPS:%=-I $TOP/%}
LIBS=${DEPS:%=$TOP/%/lib.cma}

<$TOP/mkconfig
<$TOP/mkprog
