TOP=../..

SRC=clock.ml

INCLUDES=-I $TOP/lib_core/commons \
  -I $TOP/lib_graphics/geometry -I $TOP/lib_graphics/draw \
  -I $TOP/lib_graphics/input -I $TOP/lib_graphics/ui

LIBS=$TOP/lib_core/commons/lib.cma $TOP/lib_core/regexps/lib.cma \
 $TOP/lib_graphics/geometry/lib.cma $TOP/lib_graphics/draw/lib.cma \
 $TOP/lib_graphics/input/lib.cma $TOP/lib_graphics/ui/lib.cma

SYSLIBS=unix.cma threads.cma

#CCLIBS_EXTRA=-cclib $TOP/lib_core/system/plan9/libplan9.a
EXTRA_FLAGS=-thread
EXTRALINKFLAGS=-thread

PROG=oclock

<$TOP/mkconfig

#TODO: switch to mkprog for plan9
#<$TOP/mkfiles/mkprog
<$TOP/mkfiles/mklib

install:V:
      cp $PROG $TOP/principia/ROOT/tests/bytecode/
