TOP=../..

SRC=clock.ml
PROG=oclock

DEPS=lib_core/commons lib_core/regexps \
  lib_graphics/geometry lib_graphics/draw lib_graphics/input lib_graphics/ui
SYSLIBS=unix.cma threads.cma
EXTRA_FLAGS=-thread
EXTRALINKFLAGS=-thread

INCLUDES=${DEPS:%=-I $TOP/%}
LIBS=${DEPS:%=$TOP/%/lib.cma}

<$TOP/mkconfig

#TODO: switch to mkprog for plan9
#<$TOP/mkfiles/mkprog
<$TOP/mkfiles/mklib

install:V:
      cp $PROG $TOP/principia/ROOT/tests/bytecode/
