TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=5c
LDLIBS=-lbio -l9 -lm

HFILES=\
	gc.h\
	../5l/5.out.h\
	../cc/cc.h\

OFILES=\
	cgen.$O\
	list.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	mul.$O\
	reg.$O\
	peep.$O\
        \
	pgen.$O\
	pswt.$O\
	../5l/enam.$O\

LIB=\
	../cc/cc.a\

<$TOP/mkfiles/mkone

# see 7c/mkfile for more info
p%.$O: ../cc2/p%.c
	$CC $CFLAGS ../cc2/p$stem.c
