TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml 
#SYNCWEBFLAGS=-debug

DOC=olk
#DOC_EXTRA=control_flow.tex
VERSION=1
D=..
SRC_ML=\
  $D/executables/A_out.ml $D/executables/Elf.ml \
  $D/libraries/Library_file.ml \
  $D/Load.ml $D/Resolve.ml \
  $D/Datagen.ml $D/Execgen.ml \
  $D/Layout5.ml $D/Rewrite5.ml $D/Codegen5.ml  \
  $D/Check.ml \
  $D/CLI.ml

SRC_ML_NO_MLI=\
  $D/Types.ml $D/Types5.ml \
  $D/executables/Exec_file.ml \
  $D/Main.ml \
  $D/tools/ar.ml $D/tools/nm.ml

# also $D/Parser_xxx.mly but use different -lang
SRC_VIEWS= $SRC_ML ${SRC_ML:%.ml=%.mli} $SRC_ML_NO_MLI \
   $TOP/assembler/objects/Arch_linker.ml

SRC_ORIG=olk.nw Intro.nw olk_extra.nw


<$TOP/docs/latex/mkcommon

control_flow.tex: control_flow.dot
   dot2tex $prereq --figonly > $target


# steps to build index: see builder/docs/mkfile
index:V:
#    $INDEXER -lang cmt $TOP \
#    | grep -v 'TODO_NO_SOURCE_FOUND' \
#    | grep  'mk/' \
#    > defs_and_uses.list.new
#    mv defs_and_uses.list.new defs_and_uses.list
