TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml

DOC=VCS
DOC_EXTRA=
VERSION=10

SRC1= IO_.ml \
     sha1.ml hexsha.ml \
     unzip.ml zlib.ml compression.ml \
     blob.ml tree.ml  user.ml commit.ml    objects.ml \
     refs.ml \
     index.ml \
     change.ml diff.ml \
     diff_basic.ml diff_myers.ml \
     diff_unified.ml changes.ml diffs.ml \
     repository.ml \
     client.ml client_local.ml client_git.ml clients.ml \
     cmd_.ml \
     cmd_init.ml \
     cmd_add.ml cmd_rm.ml cmd_commit.ml \
     cmd_branch.ml cmd_checkout.ml cmd_reset.ml \
     cmd_show.ml cmd_diff.ml cmd_log.ml cmd_status.ml \
     cmd_pull.ml cmd_push.ml cmd_clone.ml \
     dump.ml cmd_dump.ml cmd_test.ml \
     cmds.ml cmd_help.ml \
     main.ml

#buggy: diff_simple.ml

SRC2= IO_.mli \
     sha1.mli hexsha.mli \
     unzip.mli zlib.mli compression.mli \
     blob.mli tree.mli  user.mli commit.mli    objects.mli \
     refs.mli \
     index.mli \
     diff_basic.mli diff_myers.mli \
     change.mli diff.mli diff_unified.mli changes.mli diffs.mli \
     repository.mli \
     client.mli client_local.mli client_git.mli clients.mli \
     dump.mli  \

SRC=$SRC1 $SRC2

SRC_VIEWS=${SRC:%=../%}

SRC_ORIG=VCS.nw VCS_extra.nw

<$TOP/docs/latex/mkcommon

# steps to build index: see xix/mk/docs/mkfile instructions there
#TODO: restore
#index:V:
#	$INDEXER -lang cmt $PLAN9ML/lib_core/commons $PLAN9ML/version_control \
#    | sed -e 's#main.cmt#Main#' \
#    | grep -v 'lib_core/' \
#    | grep -v 'Common.=~' \
#    > defs_and_uses.list
#index:V:
#	echo TODO
#	touch defs_and_uses.list
