TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml

DOC=CompilerGenerator
DOC_EXTRA=
VERSION=3

D=..
# the Parser.mly are synced separately
SRC_VIEWS=\
  $D/lex/Ast.ml \
  $D/lex/Output.mli \
  $D/lex/Output.ml \
  $D/lex/Lexgen.mli \
  $D/lex/Lexgen.ml \
  $D/lex/Compact.mli \
  $D/lex/Compact.ml \
  $D/lex/CLI.mli \
  $D/lex/CLI.ml \
  $D/lex/Main.ml \
  $D/lex/Lexer.mll \
  $TOP/lib_parsing/Lexing_.mli \
  $TOP/lib_parsing/Lexing_.ml \
  $D/yacc/Ast.ml \
  $D/yacc/Check.mli \
  $D/yacc/Check.ml \
  $D/yacc/Lr0.mli \
  $D/yacc/Lr0.ml \
  $D/yacc/First_follow.mli \
  $D/yacc/First_follow.ml \
  $D/yacc/Lrtables.ml \
  $D/yacc/Slr.mli \
  $D/yacc/Slr.ml \
  $D/yacc/Lalr.mli \
  $D/yacc/Lalr.ml \
  $D/yacc/Output.mli \
  $D/yacc/Output.ml \
  $D/yacc/Dump.mli \
  $D/yacc/Dump.ml \
  $D/yacc/Tests.ml \
  $D/yacc/Lexer.mll \
  $D/yacc/CLI.mli \
  $D/yacc/CLI.ml \
  $D/yacc/Main.ml \
  $TOP/lib_parsing/Parsing_.mli \
  $TOP/lib_parsing/Parsing_.ml \

# must be in the same order than the #include in $DOC.nw for syncweb to work
SRC_ORIG=CompilerGenerator.nw CompilerGenerator_extra.nw


<$TOP/docs/latex/mkcommon

SYNCFLAGS2=-md5sum_in_auxfile -less_marks -lang ocamlyacc
sync_yacc:V:
	syncweb $SYNCFLAGS2 $SRC_ORIG $D/lex/Parser.mly
	syncweb $SYNCFLAGS2 $SRC_ORIG $D/yacc/Parser.mly


#TODO: add also $PLAN9ML/yacc! but right now conflicting module names
# are a limitations in codegraph/ocaml
#TODO: restore
#index:V:
#	$INDEXER -lang cmt $PLAN9ML/lib_core/commons $PLAN9ML/lex  \
#    | sed -e 's#main.cmt#Main#' \
#    | grep -v 'lib_core/' \
#    | grep -v 'Common.=~' \
#    > defs_and_uses.list
#index:V:
#	echo TODO index
#	touch defs_and_uses.list
