TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml

DOC=CompilerGenerator
DOC_EXTRA=
VERSION=3

# the Parser.mly are synced separately
SRC=\
  lex/Ast.ml \
  lex/Output.mli \
  lex/Output.ml \
  lex/Lexgen.mli \
  lex/Lexgen.ml \
  lex/Compact.mli \
  lex/Compact.ml \
  lex/CLI.mli \
  lex/CLI.ml \
  lex/Main.ml \
  lex/Lexer.mll \
  lib_parsing/Lexing_.mli \
  lib_parsing/Lexing_.ml \
  yacc/Ast.ml \
  yacc/Check.mli \
  yacc/Check.ml \
  yacc/Lr0.mli \
  yacc/Lr0.ml \
  yacc/First_follow.mli \
  yacc/First_follow.ml \
  yacc/Lrtables.ml \
  yacc/Slr.mli \
  yacc/Slr.ml \
  yacc/Lalr.mli \
  yacc/Lalr.ml \
  yacc/Output.mli \
  yacc/Output.ml \
  yacc/Dump.mli \
  yacc/Dump.ml \
  yacc/Tests.ml \
  yacc/Lexer.mll \
  yacc/CLI.mli \
  yacc/CLI.ml \
  yacc/Main.ml \
  lib_parsing/Parsing_.mli \
  lib_parsing/Parsing_.ml \

SRC_VIEWS=${SRC:%=$TOP/%}

# must be in the same order than the #include in $DOC.nw for syncweb to work
SRC_ORIG=CompilerGenerator.nw CompilerGenerator_extra.nw


<$TOP/docs/latex/mkcommon

SYNCFLAGS2=-md5sum_in_auxfile -less_marks -lang ocamlyacc
sync_yacc:V:
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/lex/Parser.mly
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/yacc/Parser.mly


#TODO: add also $PLAN9ML/yacc! but right now conflicting module names
# are a limitations in codegraph/ocaml
#TODO: restore
#index:V:
#	$INDEXER -lang cmt $PLAN9ML/lib_core/commons $PLAN9ML/lex  \
#    | sed -e 's#main.cmt#Main#' \
#    | grep -v 'lib_core/' \
#    | grep -v 'Common.=~' \
#    > defs_and_uses.list
#index:V:
#	echo TODO index
#	touch defs_and_uses.list
