TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml

DOC=CompilerGenerator
DOC_EXTRA=
VERSION=3

SRC=\
  lex/ast.ml \
  lex/output.mli \
  lex/output.ml \
  lex/lexgen.mli \
  lex/lexgen.ml \
  lex/compact.mli \
  lex/compact.ml \
  lex/main.ml \
  lex/lexer.mll \
  lib_parsing/lexing_.mli \
  lib_parsing/lexing_.ml \
  yacc/ast.ml \
  yacc/check.mli \
  yacc/check.ml \
  yacc/lr0.mli \
  yacc/lr0.ml \
  yacc/first_follow.mli \
  yacc/first_follow.ml \
  yacc/lrtables.ml \
  yacc/slr.mli \
  yacc/slr.ml \
  yacc/lalr.mli \
  yacc/lalr.ml \
  yacc/output.mli \
  yacc/output.ml \
  yacc/dump.mli \
  yacc/dump.ml \
  yacc/tests.ml \
  yacc/lexer.mll \
  yacc/main.ml \
  lib_parsing/parsing_.mli \
  lib_parsing/parsing_.ml \

SRC_VIEWS=${SRC:%=../../%}

# must be in the same order than the #include in $DOC.nw for syncweb to work
SRC_ORIG=CompilerGenerator.nw CompilerGenerator_extra.nw


<$TOP/docs/latex/mkcommon

#TODO!!!!
SYNCFLAGS2=-md5sum_in_auxfile -less_marks -lang ocamlyacc
#sync_yacc:
#	$(SYNCWEB_YACC) $(SRC_ORIG) $(CAML)/lex/parser.mly
#	$(SYNCWEB_YACC) $(SRC_ORIG) $(CAML)/yacc/parser.mly


#TODO: add also $PLAN9ML/yacc! but right now conflicting module names
# are a limitations in codegraph/ocaml
#TODO: restore
#index:V:
#	$INDEXER -lang cmt $PLAN9ML/lib_core/commons $PLAN9ML/lex  \
#    | sed -e 's#main.cmt#Main#' \
#    | grep -v 'lib_core/' \
#    | grep -v 'Common.=~' \
#    > defs_and_uses.list
#index:V:
#	echo TODO index
#	touch defs_and_uses.list
