TOP=..

INCLUDES=-I $TOP/lib_core/commons -I $TOP/assembler/objects -I $TOP/macroprocessor

SRC= Token_asm.ml Lexer_asm.ml \
 Parser_asm5.ml Parse_asm5.ml \
 Check_asm5.ml Resolve_labels.ml \
 CLI.ml Main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/commons/lib.cma $TOP/assembler/objects/lib.cma \
  $TOP/macroprocessor/lib.cma

# or use Principia spirit! THE assembler! so call it simply 'assembler' ? :)
PROG=5a

<$TOP/mkconfig
<$TOP/mkprog
#<$TOP/mkparser

AUTOGEN=Lexer_asm.ml Parser_asm5.ml Parser_asm5.mli

beforedepend:V: $AUTOGEN
depend:V: beforedepend

Lexer_asm.ml:D: Lexer_asm.mll
	$OCAMLLEX $prereq
Parser_asm5.ml Parser_asm5.mli: Parser_asm5.mly
	$OCAMLYACC $prereq

NUKEFILES=$AUTOGEN

#loc:V:
#   wc -l Lexer_asm.mll Parser_asm5.mly Parse_asm5.ml* Main.ml \
#    Check_asm5.ml Resolve_labels.ml \
#     $TOP/assembler/objects/Ast_asm5.ml $TOP/assembler/objects/Object_code5.ml*
