TOP=..

INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/regexps -I $TOP/assembler/objects -I $TOP/macroprocessor

# coupling: if you add a Parse_asmx.ml, please update also
#  AUTOGEN below and add ocamlyacc rules too
SRC= Token_asm.ml Lexer_asm.ml \
 Parser_asm.ml \
 Parser_asm5.ml Parse_asm5.ml \
 Parser_asmv.ml Parse_asmv.ml \
 Parser_asmi.ml Parse_asmi.ml \
 Check_asm5.ml \
 Resolve_labels.ml \
 CLI.ml Main.ml

SYSLIBS=str.cma unix.cma
LIBS= $TOP/lib_core/commons/lib.cma $TOP/lib_core/regexps/lib.cma \
  $TOP/macroprocessor/lib.cma $TOP/assembler/objects/lib.cma \
  

# or use Principia spirit! THE assembler! so call it simply 'assembler' ? :)
PROG=o5a

<$TOP/mkconfig
<$TOP/mkfiles/mkprog
#<$TOP/mkparser

AUTOGEN=Lexer_asm.ml \
  Parser_asm5.ml Parser_asm5.mli \
  Parser_asmv.ml Parser_asmv.mli \
  Parser_asmi.ml Parser_asmi.mli \

beforedepend:V: $AUTOGEN
depend:V: beforedepend

Lexer_asm.ml:D: Lexer_asm.mll
	$OCAMLLEX $prereq
Parser_asm5.ml Parser_asm5.mli: Parser_asm5.mly
	$OCAMLYACC $prereq
Parser_asmv.ml Parser_asmv.mli: Parser_asmv.mly
	$OCAMLYACC $prereq
Parser_asmi.ml Parser_asmi.mli: Parser_asmi.mly
	$OCAMLYACC $prereq

NUKEFILES=$AUTOGEN
