# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/commons -I $TOP/formats/objects -I $TOP/macroprocessor

SRC= parser_asm5.ml lexer_asm5.ml parse_asm5.ml \
 resolve_labels5.ml \
 main.ml

SYSLIBS=str.cma
LIBS=$TOP/commons/lib.cma $TOP/formats/objects/lib.cma \
  $TOP/macroprocessor/lib.cma

# or use Principia spirit! THE assembler! so call it simply 'assembler' ? :)
PROG=5a

<$TOP/mkprog

beforedepend:V: lexer_asm5.ml parser_asm5.ml parser_asm5.mli
depend:V: beforedepend

distclean:V: clean
	rm -f lexer_asm5.ml
	rm -f parser_asm5.ml parser_asm5.mli parser_asm5.output

lexer_asm5.ml:D: lexer_asm5.mll
	$OCAMLLEX $prereq
parser_asm5.ml parser_asm5.mli: parser_asm5.mly
	$OCAMLYACC $prereq

loc:V:
   wc -l globals.ml lexer_asm5.mll parser_asm5.mly parse_asm5.ml* main.ml $TOP/formats/objects/ast_asm5.ml $TOP/formats/objects/object_code5.ml*
