TOP=..

# We could have lexing.ml and parsing.ml. It would work with ocamlc,
# but not with ocamlopt :(

INCLUDES=-I $TOP/lib_core/commons

# Note that those files are sync'ed by syncweb from principia/generators

SRC=Lexing_.ml Parsing_.ml

<$TOP/mkconfig
<$TOP/mkfiles/mklib
