(* generated by ocamltarzan with: camlp4o -o /tmp/yyy.ml -I pa/ pa_type_conv.cmo pa_vof.cmo  pr_o.cmo /tmp/xxx.ml  *)

open Types5

module Ocaml = OCaml

module A = Meta_ast_asm5

let vof_filename = Ocaml.vof_string

let vof_loc (v1, v2) =
  let v1 = vof_filename v1
  and v2 = A.vof_pos v2
  in Ocaml.VTuple [ v1; v2 ]

let rec vof_code (v1, v2) =
  let v1 = vof_instr v1 and v2 = vof_loc v2 in Ocaml.VTuple [ v1; v2 ]
and vof_instr =
  function
  | TEXT ((v1, v2, v3)) ->
      let v1 = A.vof_global v1
      and v2 = A.vof_attributes v2
      and v3 = Ocaml.vof_int v3
      in Ocaml.VSum (("TEXT", [ v1; v2; v3 ]))
  | WORD v1 -> let v1 = A.vof_imm_or_ximm v1 in Ocaml.VSum (("WORD", [ v1 ]))
  | I ((v1, v2)) ->
      let v1 = A.vof_instr v1
      and v2 = A.vof_condition v2
      in Ocaml.VSum (("I", [ v1; v2 ]))
