# -*- sh -*-

TOP=..
# need -I macroprocessor/ because object files contains Location_cpp data
# but in theory the linker does not need it
INCLUDES=-I $TOP/lib_core/commons -I $TOP/macroprocessor -I $TOP/assembler/objects -I $TOP/linker/executables -I $TOP/linker/libraries

SRC= Flags.ml\
 Types.ml Types5.ml Typesv.ml \
 Arch_linker.ml \
 Load.ml Check.ml Resolve.ml \
 Rewrite.ml Rewrite5.ml Rewritev.ml \
 Layout.ml Layout5.ml Layoutv.ml \
 Codegen.ml Codegen5.ml Codegenv.ml \
 Datagen.ml \
 Execgen.ml \
 CLI.ml Main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/commons/lib.cma $TOP/macroprocessor/lib.cma $TOP/assembler/objects/lib.cma $TOP/linker/executables/lib.cma $TOP/linker/libraries/lib.cma

# or use Principia spirit! THE linker! so call it simply 'linker' ? :)
PROG=o5l

<$TOP/mkconfig
<$TOP/mkfiles/mkprog

loc:V:
   wc -l $SRC *.mli
