(* generated by ocamltarzan with: camlp4o -o /tmp/yyy.ml -I pa/ pa_type_conv.cmo pa_vof.cmo  pr_o.cmo /tmp/xxx.ml  *)

open Storage

let vof_t =
  function
  | Auto -> Ocaml.VSum (("Auto", []))
  | Param -> Ocaml.VSum (("Param", []))
  | Extern -> Ocaml.VSum (("Extern", []))
  | Global -> Ocaml.VSum (("Global", []))
  | Static -> Ocaml.VSum (("Static", []))
  
let vof_intsize =
  function
  | Char -> Ocaml.VSum (("Char", []))
  | Short -> Ocaml.VSum (("Short", []))
  | Int -> Ocaml.VSum (("Int", []))
  | Long -> Ocaml.VSum (("Long", []))
  | VLong -> Ocaml.VSum (("VLong", []))
  
let vof_floatsize =
  function
  | Float -> Ocaml.VSum (("Float", []))
  | Double -> Ocaml.VSum (("Double", []))
  
let vof_stringsize =
  function
  | String -> Ocaml.VSum (("String", []))
  | Unicode -> Ocaml.VSum (("Unicode", []))
  

