(* generated by ocamltarzan with: camlp4o -o /tmp/yyy.ml -I pa/ pa_type_conv.cmo pa_vof.cmo  pr_o.cmo /tmp/xxx.ml  *)

open Type

let vof_blockid v = Ocaml.vof_int v
  
let vof_sign =
  function
  | Signed -> Ocaml.VSum (("Signed", []))
  | Unsigned -> Ocaml.VSum (("Unsigned", []))

let vof_fullname (v1, v2) =
  let v1 = Ocaml.vof_string v1 and v2 = vof_blockid v2 in 
  Ocaml.VTuple [ v1; v2 ]

let vof_struct_kind =
  function
  | Struct -> Ocaml.VSum (("Struct", []))
  | Union -> Ocaml.VSum (("Union", []))

  
let rec vof_t =
  function
  | TVoid -> Ocaml.VSum (("TVoid", []))
  | TChar v1 -> let v1 = vof_sign v1 in Ocaml.VSum (("TChar", [ v1 ]))
  | TShort v1 -> let v1 = vof_sign v1 in Ocaml.VSum (("TShort", [ v1 ]))
  | TInt v1 -> let v1 = vof_sign v1 in Ocaml.VSum (("TInt", [ v1 ]))
  | TLong v1 -> let v1 = vof_sign v1 in Ocaml.VSum (("TLong", [ v1 ]))
  | TVLong v1 -> let v1 = vof_sign v1 in Ocaml.VSum (("TVLong", [ v1 ]))
  | TEnum -> Ocaml.VSum (("TEnum", []))
  | TFloat -> Ocaml.VSum (("TFloat", []))
  | TDouble -> Ocaml.VSum (("TDouble", []))
  | TPointer v1 -> let v1 = vof_t v1 in Ocaml.VSum (("TPointer", [ v1 ]))
  | TArray v1 -> let v1 = vof_t v1 in Ocaml.VSum (("TArray", [ v1 ]))
  | TFunc ((v1, v2)) ->
      let v1 = vof_t v1
      and v2 = Ocaml.vof_list vof_t v2
      in Ocaml.VSum (("TFunc", [ v1; v2 ]))
  | TStructName ((v1, v2)) ->
      let v1 = vof_struct_kind v1
      and v2 = vof_fullname v2
      in Ocaml.VSum (("TStructName", [ v1; v2 ]))
  
let vof_qualifier =
  function
  | Volatile -> Ocaml.VSum (("Volatile", []))
  | Const -> Ocaml.VSum (("Const", []))
  
let vof_structdef v1 =
  Ocaml.vof_list
    (fun (v1, v2) ->
      let v1 = Ocaml.vof_string v1
      and v2 = vof_t v2
      in Ocaml.VTuple [ v1; v2 ])
    v1
  

