(* generated by ocamltarzan with: camlp4o -o /tmp/yyy.ml -I pa/ pa_type_conv.cmo pa_vof.cmo  pr_o.cmo /tmp/xxx.ml  *)

open Storage

let vof_t =
  function
  | Local -> Ocaml.VSum (("Local", []))
  | Param -> Ocaml.VSum (("Param", []))
  | Extern -> Ocaml.VSum (("Extern", []))
  | Global -> Ocaml.VSum (("Global", []))
  | Static -> Ocaml.VSum (("Static", []))

