TOP=..

INCLUDES=-I $TOP/lib_core/commons \
  -I $TOP/macroprocessor \
  -I $TOP/assembler/objects

#coupling: dune file library (modules ...)
SRC= Flags.ml \
  Type.ml Meta_type.ml   Storage.ml Meta_storage.ml \
  Ast.ml Meta_ast.ml \
  Dumper_.ml \
  Globals.ml \
  Error.ml \
  Parser.ml Lexer.ml Parse.ml \
  Arch_compiler.ml \
  Check.ml Eval_const.ml Typecheck.ml \
  Rewrite.ml \
  Arch5.ml Archv.ml Codegen.ml \
  CLI.ml Main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/commons/lib.cma \
 $TOP/macroprocessor/lib.cma \
 $TOP/assembler/objects/lib.cma

PROG=o5c

<$TOP/mkconfig
<$TOP/mkfiles/mkprog
<$TOP/mkfiles/mkparser

#coupling: mkcommon
Main.cmo: Main.ml
	  $OCAMLC $COMPFLAGS $INCLUDES -pp ../scripts/remove_xix_open.sh -c Main.ml
Main.cmx: Main.ml
	  $OCAMLOPT $OPTFLAGS $INCLUDES -pp ../scripts/remove_xix_open.sh -c Main.ml
