# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/commons -I $TOP/lib_core

SRC= globals.ml flags.ml \
  ast.ml type.ml storage.ml \
  preprocessor.ml \
  error.ml \
  parser.ml lexer.ml parse.ml \
  main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/lib.cma $TOP/commons/lib.cma

PROG=5c

<$TOP/mkprog

beforedepend:V: lexer.ml parser.ml parser.mli


depend:V: beforedepend

distclean:V: clean
	rm -f lexer.ml
	rm -f parser.ml parser.mli parser.output

lexer.ml: lexer.mll
	$OCAMLLEX $prereq

parser.ml parser.mli: parser.mly
	$OCAMLYACC $prereq


loc:V:
	mk distclean
	wc -l *.ml*
