TOP=..

INCLUDES=-I $TOP/lib_core/commons \
  -I $TOP/macroprocessor \
  -I $TOP/assembler/objects

SRC= Flags.ml \
  Type.ml Meta_type.ml   Storage.ml Meta_storage.ml \
  Ast.ml Meta_ast.ml \
  Dumper_.ml \
  Globals.ml \
  Error.ml \
  Parser.ml Lexer.ml Parse.ml \
  Arch_compiler.ml \
  Check.ml Eval_const.ml Typecheck.ml \
  Rewrite.ml \
  Arch5.ml Codegen5.ml \
  CLI.ml Main.ml

SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/commons/lib.cma \
 $TOP/macroprocessor/lib.cma \
 $TOP/assembler/objects/lib.cma

PROG=5c

<$TOP/mkconfig
<$TOP/mkprog
<$TOP/mkparser
