TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml 
SYNCWEBFLAGS=-debug

DOC=Mk
VERSION=1
D=..
SRC_ML=\
  $D/Parse.ml \
  $D/Shellenv.ml $D/Shell.ml \
  $D/Percent.ml $D/Env.ml  $D/Eval.ml \
  $D/File.ml $D/Graph.ml \
  $D/Scheduler.ml $D/Outofdate.ml \
  $D/CLI.ml
SRC_ML_NO_MLI=$D/Ast.ml $D/Globals.ml $D/Flags.ml $D/Main.ml $D/Rules.ml $D/Job.ml

SRC_VIEWS= $SRC_ML ${SRC_ML:%.ml=%.mli} $SRC_ML_NO_MLI

SRC_ORIG=Mk.nw Intro.nw


<$TOP/docs/latex/mkcommon
