TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml 
#SYNCWEBFLAGS=-debug

DOC=Mk
VERSION=1
D=..
SRC_ML=\
  $D/Parse.ml \
  $D/Shellenv.ml $D/Shell.ml \
  $D/Percent.ml $D/Env.ml  $D/Eval.ml \
  $D/File.ml $D/Graph.ml \
  $D/Scheduler.ml $D/Outofdate.ml \
  $D/CLI.ml
SRC_ML_NO_MLI=$D/Ast.ml $D/Globals.ml $D/Flags.ml $D/Main.ml $D/Rules.ml $D/Job.ml

SRC_VIEWS= $SRC_ML ${SRC_ML:%.ml=%.mli} $SRC_ML_NO_MLI ../Lexer.mll ../Lexer.mli

SRC_ORIG=Mk.nw Intro.nw Mk_extra.nw


<$TOP/docs/latex/mkcommon

sync_yacc:VI:
        $SYNCWEB -md5sum_in_auxfile -less_marks -lang ocamlyacc  $SRC_ORIG \
            ../Parser.mly

# steps to build index:
# - remove wrapped true in dune file
# - cd ~/xix; mk nuke; make clean
# # make all to produce .cmt for all of xix otherwise not enough
# - make build-dune
# - rm -rf _build/.../mk/tests
# - codegraph_build -lang cmt .
# # look if codegraph looks ok
# - cg .
# - cd mk/docs
# - mk index
# - mk pdf
# => DONE! Mk.pdf should now have indexes!
index:V:
    $INDEXER -lang cmt $TOP \
    | grep -v 'TODO_NO_SOURCE_FOUND' \
    | grep  'mk/' \
    > defs_and_uses.list.new
    mv defs_and_uses.list.new defs_and_uses.list


#    | sed -e 's#main.cmt#Main#' \
#    | grep -v 'Pervasives.:=' \
#    | grep -v 'Pervasives.~' \
#    | grep -v 'stdlib/' \
