TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=8a
LDLIBS=-lbio -l9 -lm

HFILES=\
	a.h\
	y.tab.h\
	../8l/8.out.h\

OFILES=\
	y.tab.$O\
	lex.$O\
	../8l/enam.$O\

YFILES=a.y

<$TOP/mkfiles/mkone

lex.$O:	../cc/macbody ../cc/lexbody
