# -*- sh -*-
TOP=../..

INCLUDES= -I ../core -I ../concurrency_/ -I ../base -I ../concurrency -I ../memory -I $TOP/lib_core/commons -I +threads
SRC= Process.ml Kproc.ml \
  sysexec.ml sysrfork.ml sysexits.ml


<$TOP/mkconfig
<$TOP/mkfiles/mklib
