# -*- sh -*-
TOP=../..

INCLUDES=-I $TOP/lib_core/commons -I $TOP/macroprocessor

SRC=Ast_asm.ml \
  Ast_asm5.ml Meta_ast_asm5.ml \
  Ast_asmv.ml \
  Object_file.ml \
  Arch_linker.ml

<$TOP/mkconfig
<$TOP/mkfiles/mklib
