# -*- sh -*-

TOP=../..
INCLUDES=-I .

SRC=Cap.ml \
 CapStdlib.ml CapSys.ml CapUnix.ml \
 Common.ml common2.ml \
 Dumper.ml OCaml.ml \
 Console.ml UConsole.ml CapConsole.ml \
 Logs.ml \
 Fpath.ml Chan.ml CapFS.ml IO.ml \
 Date.ml

<$TOP/mkconfig
<$TOP/mklib
