# -*- sh -*-

TOP=../..
INCLUDES=-I .

#coupling: dune '(modules ...)' stanza
SRC=Cap.ml \
 CapStdlib.ml CapSys.ml CapUnix.ml \
 Common.ml common2.ml \
 Dumper.ml OCaml.ml \
 Console.ml UConsole.ml \
 Fpath.ml Fpath_.ml \
 Logs.ml \
 Chan.ml UChan.ml CapFS.ml IO.ml \
 Date.ml \
 Exception.ml Exit.ml

<$TOP/mkconfig
<$TOP/mklib
