# -*- sh -*-
# The lexer generator

TOP=..
INCLUDES=-I $TOP/lib_core

SRC= ast.ml \
 parser.ml lexer.ml \
 lexgen.ml compact.ml output.ml \
 main.ml

SYSLIBS=
LIBS=$TOP/lib_core/lib.cma

PROG=ocamllex

<$TOP/mkprog

beforedepend:V: lexer.ml parser.ml parser.mli
depend:V: beforedepend

distclean:V: clean
	rm -f lexer.ml parser.ml parser.mli 

lexer.ml: lexer.mll
	$OCAMLLEX $prereq
parser.ml parser.mli: parser.mly
	$OCAMLYACC $prereq
	perl -p -i -e 's#/\*\(\*[sex]: .* \*\)\*/##' parser.ml
#pad: this  perl thing is just because ocamlyacc does not handle well
# syncweb special comment at the very end


loc:V:
   wc -l globals.ml lexer_asm5.mll parser_asm5.mly parse_asm5.ml* main.ml $TOP/formats/objects/ast_asm5.ml $TOP/formats/objects/object_code5.ml*
