# The lexer generator

TOP=..

# Just for Set_ and Map_. lex/ is synced almost as-is with ocaml-light/lex
# so keep the dependencies to xix to the minimum.
INCLUDES=-I $TOP/lib_core/commons

# Note that those files are sync'ed by syncweb from principia/generators

SRC= Ast.ml \
 Parser.ml Lexer.ml \
 Lexgen.ml Compact.ml Output.ml \
 CLI.ml Main.ml

SYSLIBS=
LIBS=$TOP/lib_core/commons/lib.cma

PROG=ocamllex

<$TOP/mkconfig
<$TOP/mkprog

#<$TOP/mkparser

AUTOGEN=Lexer.ml Parser.ml Parser.mli
NUKEFILES=$AUTOGEN

beforedepend:V: $AUTOGEN
depend:V: beforedepend

Lexer.ml:D: Lexer.mll
	$OCAMLLEX $prereq
Parser.ml Parser.mli: Parser.mly
	$OCAMLYACC $prereq
	perl -p -i -e 's#/\*\(\*[sex]: .* \*\)\*/##' Parser.ml
#pad: this  perl thing is just because ocamlyacc does not handle well
# syncweb special comment at the very end


loc:V:
   wc -l globals.ml lexer_asm5.mll parser_asm5.mly parse_asm5.ml* main.ml $TOP/formats/objects/ast_asm5.ml $TOP/formats/objects/object_code5.ml*
