TOP=../..

PROGS=ocat opwd

INCLUDES=-I $TOP/lib_core/commons
SYSLIBS=str.cma unix.cma
LIBS=$TOP/lib_core/commons/lib.cma

all:V: $PROGS

<$TOP/mkconfig
<$TOP/mkfiles/mkcommon

o%: %.ml
   $OCAMLC $LINKFLAGS $EXTRALINKFLAGS $INCLUDES $SYSLIBS $LIBS $prereq $CCLIBS -o $target


clean nuke:V:
      rm -f *.cm[ioxa]
      rm -f $PROGS
