# -*- sh -*-
TOP=../..

INCLUDES= -I ../core -I ../concurrency_/ -I ../base -I ../concurrency -I ../memory -I ../processes -I $TOP/lib_core/commons -I +threads
SRC= Rendez.ml Hz_sched.ml Scheduler.ml


<$TOP/mkconfig
<$TOP/mkfiles/mklib
