# -*- sh -*-

TOP=../..
INCLUDES=-I .

# coupling: if you add a file, you also need to add an entry
#  for the %.cmi: stdlib.cmi below
SRC=camlinternalFormatBasics.ml Stdlib.ml \
   Bool.ml \
   Option.ml Either.ml Result.ml \

<$TOP/mkconfig
<$TOP/mklib

Bool.cmi: Stdlib.cmi
Option.cmi: Stdlib.cmi
Either.cmi: Stdlib.cmi
Result.cmi: Stdlib.cmi

camlinternalFormatBasics.cmo: camlinternalFormatBasics.ml
	$OCAMLC $COMPFLAGS $INCLUDES -nopervasives -c camlinternalFormatBasics.ml

Stdlib.cmo: Stdlib.ml
	$OCAMLC $COMPFLAGS $INCLUDES -nopervasives -c Stdlib.ml

Stdlib.cmi: Stdlib.mli
	$OCAMLC $COMPFLAGS $INCLUDES -nopervasives -c Stdlib.mli
