# -*- sh -*-

TOP=../..
INCLUDES=-I .

# coupling: if you add a file, you also need to add an entry
#  for the %.cmi: stdlib.cmi below
SRC=camlinternalFormatBasics.ml stdlib.ml \
   bool.ml \
   option.ml either.ml result.ml

<$TOP/mkconfig
<$TOP/mklib

bool.cmi: stdlib.cmi
option.cmi: stdlib.cmi
either.cmi: stdlib.cmi
result.cmi: stdlib.cmi

camlinternalFormatBasics.cmo: camlinternalFormatBasics.ml
	$OCAMLC $COMPFLAGS $INCLUDES -nopervasives -c camlinternalFormatBasics.ml

stdlib.cmo: stdlib.ml
	$OCAMLC $COMPFLAGS $INCLUDES -nopervasives -c stdlib.ml

stdlib.cmi: stdlib.mli
	$OCAMLC $COMPFLAGS $INCLUDES -nopervasives -c stdlib.mli


