TOP=..

INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_core/regexps

#coupling: library stanza in dune file and docs/mkfile:SRC_VIEW
SRC= Globals.ml Flags.ml \
  Ast.ml   Parser.ml Lexer.ml Parse.ml \
  Shellenv.ml Shell.ml \
  Percent.ml Env.ml Rules.ml   Eval.ml \
  File.ml Graph.ml \
  Job.ml   Scheduler.ml Outofdate.ml \
  CLI.ml Main.ml

SYSLIBS=unix.cma
LIBS=$TOP/lib_core/commons/lib.cma $TOP/lib_core/regexps/lib.cma

PROG=omk

<$TOP/mkconfig
<$TOP/mkfiles/mkprog
<$TOP/mkfiles/mkparser

#coupling: mkcommon
Main.cmo: Main.ml
	  $OCAMLC $COMPFLAGS $INCLUDES -pp ../scripts/remove_xix_open.sh -c Main.ml
Main.cmx: Main.ml
	  $OCAMLOPT $OPTFLAGS $INCLUDES -pp ../scripts/remove_xix_open.sh -c Main.ml
