# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/lib_core/commons

SRC= flags_cpp.ml location_cpp.ml ast_cpp.ml lexer_cpp.ml preprocessor.ml \
 parse_cpp.ml

<$TOP/mklib

beforedepend:V: lexer_cpp.ml

depend:V: beforedepend

distclean:V: clean
	rm -f lexer_cpp.ml

lexer_cpp.ml:D: lexer_cpp.mll
	$OCAMLLEX $prereq


loc:V:
	mk distclean
	wc -l *.ml*
