TOP=..

INCLUDES=-I $TOP/lib_core/commons

SRC= Flags_cpp.ml Location_cpp.ml Ast_cpp.ml Lexer_cpp.ml Preprocessor.ml \
 Parse_cpp.ml

<$TOP/mkconfig
<$TOP/mkfiles/mklib

#<$TOP/mkparser

AUTOGEN=Lexer_cpp.ml
NUKEFILES=$AUTOGEN

beforedepend:V: $AUTOGEN
depend:V: beforedepend

Lexer_cpp.ml:D: Lexer_cpp.mll
	$OCAMLLEX $prereq
