TOP=..

INCLUDES=-I $TOP/lib_core/commons

SRC= flags_cpp.ml location_cpp.ml ast_cpp.ml lexer_cpp.ml preprocessor.ml \
 parse_cpp.ml

<$TOP/mklib

#<$TOP/mkparser

AUTOGEN=lexer_cpp.ml
NUKEFILES=$AUTOGEN

beforedepend:V: $AUTOGEN
depend:V: beforedepend

lexer_cpp.ml:D: lexer_cpp.mll
	$OCAMLLEX $prereq
