TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml 
#SYNCWEBFLAGS=-debug

DOC=oas
#DOC_EXTRA=control_flow.tex
VERSION=1
D=..
SRC_ML=\
  $D/objects/Object_file.ml \
  $D/Parse_asm5.ml \
  $D/Resolve_labels.ml \
  $D/CLI.ml

SRC_ML_NO_MLI=\
  $D/Token_asm.ml \
  $D/objects/Ast_asm.ml $D/objects/Ast_asm5.ml \
  $D/Parser_asm.ml \
  $D/Main.ml

# also $D/Parser_xxx.mly but use different -lang
SRC_VIEWS= $SRC_ML ${SRC_ML:%.ml=%.mli} $SRC_ML_NO_MLI $D/Lexer_asm.mll

SRC_ORIG=oas.nw Intro.nw oas_extra.nw


<$TOP/docs/latex/mkcommon

sync_yacc:VI:
        $SYNCWEB -md5sum_in_auxfile -less_marks -lang ocamlyacc  $SRC_ORIG \
            $D/Parser_asm5.mly

control_flow.tex: control_flow.dot
   dot2tex $prereq --figonly > $target


# steps to build index: see builder/docs/mkfile
index:V:
#    $INDEXER -lang cmt $TOP \
#    | grep -v 'TODO_NO_SOURCE_FOUND' \
#    | grep  'mk/' \
#    > defs_and_uses.list.new
#    mv defs_and_uses.list.new defs_and_uses.list
