TOP=../../../..

DEPS=lib_core/commons \
     lib_gui/lib_graphics/geometry\
     lib_gui/lib_graphics/draw\

SRC=hellodraw.ml

PROG=hellodraw
SYSLIBS=unix.cma graphics.cma


INCLUDES=${DEPS:%=-I $TOP/%}
LIBS=${DEPS:%=$TOP/%/lib.cma}

<$TOP/mkconfig
<$TOP/mkprog
