TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=va
LDLIBS=-lbio -l9 -lm

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../vl/v.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

YFLAGS=-D1 -d

<$TOP/mkfiles/mkone

lex.$O:	../cc/macbody ../cc/lexbody

#$ROOT/$OBJDIR/lib/libcc.a:
#	cd ../cc
#	mk $MKFLAGS install
#	mk $MKFLAGS clean
