# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/commons

SRC= ksym.ml

SYSLIBS=str.cma
LIBS=$TOP/commons/lib.cma

# or use Principia spirit! THE assembler! so call it simply 'assembler' ? :)
PROG=ksym

<$TOP/mkprog
