# -*- sh -*-

TOP=..
INCLUDES=-I $TOP/lib_core/commons

SRC= ksym.ml

SYSLIBS=
LIBS=$TOP/lib_core/commons/lib.cma

# or use Principia spirit! THE assembler! so call it simply 'assembler' ? :)
PROG=ksym

<$TOP/mkfiles/mkprog
