TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=vl
LDLIBS=-lbio -l9 -lm

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	\
        enam.$O\
	elf.$O\

#$TARGMODEL.$O\

HFILES= l.h v.out.h $TOP/include/ar.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: v.out.h
	sh mkenam

#elf.$O:	../ld/elf.c
#	$CC $CFLAGS ../ld/elf.c

%.$O:	../ld/%.c
	$CC $CFLAGS ../ld/$stem.c

#$TARGMODEL.$O:	../ld/$TARGMODEL.c
#	$CC $CFLAGS ../ld/$TARGMODEL.c
