TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=6c
LDLIBS=-lbio -l9 -lm

HFILES=\
	gc.h\
	../6l/6.out.h\
	../cc/cc.h\

OFILES=\
	cgen.$O\
	list.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	div.$O\
	mul.$O\
	reg.$O\
	peep.$O\
	machcap.$O\
        \
	pgen.$O\
	pswt.$O\
	../6l/enam.$O\

LIB=\
	../cc/cc.a\

<$TOP/mkfiles/mkone

# see 7c/mkfile for more info
p%.$O: ../cc2/p%.c
	$CC $CFLAGS ../cc2/p$stem.c
