# Build XiX via docker.
# We are testing mostly the bootstrap-mk.sh and mk way to build xix (not dune).
# See also Dockerfile at the root of the project.

name: docker

on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # optional if don't need multi-arch build
      - uses: docker/setup-buildx-action@v3
      # alt: make build-docker
      - run: docker build -t xix .
      - run: docker build -f Dockerfile.light -t xix-light .
