# Build xix via docker

name: docker

on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # optional if don't need multi-arch build
      - uses: docker/setup-buildx-action@v3
      # alt: make build-docker
      - run: docker build -t xix .
