# Build XiX via docker.
# We are testing mostly the bootstrap-mk.sh and mk way to build xix (not dune).
# See also Dockerfile at the root of the project.

name: docker

on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml:
          #not since I've removed the use of Stdcompat in a few files
          #- 4.12.0
          - 4.14.2
          - 5.1.1
          # the one after don't work because of ppxlib constraint in xix.opam
          #- 5.2.1
          #- 5.3.0
    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag "syncweb" --build-arg OCAML_VERSION=${{matrix.ocaml}} .
  build-light:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -f Dockerfile.light --tag xix-light .
