# Build XiX via Nix.
# We are testing mostly the dune way to build XiX (not mk).

name: nix

on:
  workflow_dispatch: null
  pull_request_target: {}
  push:
    branches: [master]

jobs:
  job:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@main
      #- name: Check Flake Validity
      #  uses: DeterminateSystems/flake-checker-action@main
      - name: Build Nix shell
        run: make shell
      - name: Build XiX using Nix
        run: |
          nix-shell --run '
            ./configure
            make
          '

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
