# Build XiX via Nix on Linux and MacOS with OCaml 5.2.1
# We are testing the dune way to build XiX (not mk).
# See also shell.nix at the root of the project.

name: nix

on:
  workflow_dispatch: null
  pull_request_target: {}
  push:
    branches: [master]

jobs:
  job:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Nix shell
        run: make shell
      # UGLY: even with (dirs \ principia) directive dune complains under nix
      - run: rm -f principia
      - name: Build XiX using Nix
        run: |
          nix-shell --run '
            ./configure
            make
            make test
          '

