# Build xix via Nix

name: nix

on:
  workflow_dispatch: null
  pull_request_target: {}
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - name: Enter nix-shell and build
      run: |
        nix-shell --run '
          eval $(opam env --root=$PWD/.opam --switch=$PWD/_opam_switch)
          dune build
        '
