# -*- sh -*-
# The parser generator

TOP=../..

# Just for Set_ and Map_. yacc/ might be synced with ocaml-light/yacc
# at some point so keep the dependencies to xix to the minimum.
INCLUDES=-I $TOP/lib_core/commons -I $TOP/lib_parsing

# Note that those files are sync'ed by syncweb from principia/generators

SRC= Ast.ml\
 Parser.ml Lexer.ml\
 Check.ml\
 Lr0.ml First_follow.ml Lrtables.ml Slr.ml Lalr.ml \
 Output.ml Dump.ml \
 Tests.ml CLI.ml Main.ml

# need str.cma and commons/lib.cma because of Common.Stack_.nth
# but we could inline this function in parsing_.ml to avoid those deps.
SYSLIBS=str.cma
LIBS=$TOP/lib_core/commons/lib.cma \
  $TOP/lib_parsing/lib.cma

PROG=ocamlyacc

<$TOP/mkconfig
<$TOP/mkfiles/mkprog

#<$TOP/mkparser

AUTOGEN=Lexer.ml Parser.ml Parser.mli
NUKEFILES=$AUTOGEN

beforedepend:V: $AUTOGEN
depend:V: beforedepend

Lexer.ml:D: Lexer.mll
	$OCAMLLEX $prereq
Parser.ml Parser.mli: Parser.mly
	$OCAMLYACC $prereq
	perl -p -i -e 's#/\*\(\*[sex]: .* \*\)\*/##' Parser.ml
#pad: this  perl thing is just because ocamlyacc does not handle well
# syncweb special comment at the very end
